services:
  - type: web
    name: my-todo-app-frontend
    env: static
    buildCommand: cd frontend/notes-app && npm install && npm run build
    staticPublishPath: frontend/notes-app/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
