services:
  - type: web
    name: my-todo-app-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
